[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/pow",
    "crates/chain",
    "crates/vm",
    "crates/zk",
    "crates/node",
]

[workspace.package]
version = "0.1.7"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/blocklechain/blockle"
homepage = "https://blockle.org"

[workspace.dependencies]
scrypt = { version = "0.11", default-features = false }
blake3 = "1"
blake2 = "0.10"
tiny-keccak = { version = "2", features = ["cshake"] }
eaglesong = "0.1"
rs-x11-hash = "0.1"
chacha20poly1305 = "0.10"
rpassword = "7"
blake2b_simd = "1"
primitive-types = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
thiserror = "1"
anyhow = "1"
hex = "0.4"
sha2 = "0.10"
fips204 = "0.4"
fips203 = "0.4"
winterfell = "0.13"
bech32 = "0.11"
clap = { version = "4", features = ["derive"] }

blockle-core = { path = "crates/core", version = "0.1.7" }
blockle-zk = { path = "crates/zk", version = "0.1.7" }
blockle-pow = { path = "crates/pow", version = "0.1.7" }
blockle-chain = { path = "crates/chain", version = "0.1.7" }
blockle-vm = { path = "crates/vm", version = "0.1.7" }

[profile.release]
lto = "thin"
