//! Pool configuration (TOML), generated by `add-chain` and consumed by
//! `serve`.

use std::fs;
use std::path::Path;

use anyhow::{anyhow, Context, Result};
use serde::{Deserialize, Serialize};

use crate::adapters::bitcoin::{AuxConfig, FieldMap};

#[derive(Serialize, Deserialize, Clone)]
pub struct PoolConfig {
    pub chain: ChainSection,
    pub pool: PoolSection,
    /// blockle.biz registration (written by `blockle register`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub biz: Option<BizSection>,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct BizSection {
    pub url: String,
    pub pool_id: String,
    pub token: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct ChainSection {
    pub name: String,
    pub rpc: String,
    /// Adapter family: "bitcoin-family" is built in; anything else needs a
    /// custom adapter.
    pub adapter: String,
    pub algorithm: String,
    #[serde(default)]
    pub field_map: FieldMap,
    /// Merged-mined (AuxPoW) auxiliary chains.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub aux: Vec<AuxConfig>,
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(default)]
pub struct PoolSection {
    pub stratum: String,
    pub dashboard: String,
    /// Hex scriptPubKey that receives coinbase rewards.
    pub payout_script: String,
    /// Chain-side hot wallet address (receives coinbase; keys stay in the
    /// chain node's own wallet). Auto-created by `blockle add-chain` when
    /// the chain RPC has wallet support.
    #[serde(skip_serializing_if = "String::is_empty")]
    pub hot_address: String,
    /// Chain-side cold/payout wallet address for operator settlement.
    #[serde(skip_serializing_if = "String::is_empty")]
    pub payout_address: String,
    /// BLOCK address that receives this pool's Proof-of-Blocks rewards.
    #[serde(skip_serializing_if = "String::is_empty")]
    pub blockle_address: String,
    /// Payout scheme: solo | pplns | prop | pps.
    pub scheme: String,
    /// Pool fee in percent.
    pub fee_percent: f64,
    /// PPLNS window size (shares).
    pub pplns_window: usize,
    /// blockle.biz heartbeat interval (seconds).
    pub heartbeat_secs: u64,
}

impl Default for PoolSection {
    fn default() -> Self {
        PoolSection {
            stratum: "0.0.0.0:3333".into(),
            dashboard: "127.0.0.1:8080".into(),
            // OP_TRUE — fine for sim/test chains; real pools set their own.
            payout_script: "51".into(),
            hot_address: String::new(),
            payout_address: String::new(),
            blockle_address: String::new(),
            scheme: "pplns".into(),
            fee_percent: 1.0,
            pplns_window: 10_000,
            heartbeat_secs: 60,
        }
    }
}

impl PoolConfig {
    pub fn load(path: &Path) -> Result<Self> {
        let raw = fs::read_to_string(path)
            .with_context(|| format!("cannot read {}", path.display()))?;
        toml::from_str(&raw).map_err(|e| anyhow!("bad config {}: {e}", path.display()))
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        fs::write(path, toml::to_string_pretty(self)?)?;
        Ok(())
    }
}
