//! Starter-adapter generation for chains the prober can't fully classify:
//! a prefilled config manifest (everything that *was* detected) plus a Rust
//! adapter stub with the undetected parts marked.

use std::fs;
use std::path::Path;

use anyhow::Result;

use crate::config::{ChainSection, PoolConfig, PoolSection};
use crate::probe::ChainProfile;

pub fn generate(profile: &ChainProfile, name: &str, out_dir: &Path) -> Result<Vec<String>> {
    fs::create_dir_all(out_dir)?;
    let mut written = Vec::new();

    let config = PoolConfig {
        chain: ChainSection {
            name: name.to_string(),
            rpc: profile.rpc_url.clone(),
            adapter: "custom".into(),
            algorithm: profile.algorithm.to_string(),
            field_map: profile.field_map.clone().unwrap_or_default(),
            aux: vec![],
        },
        pool: PoolSection::default(),
        biz: None,
    };
    let cfg_path = out_dir.join(format!("{name}.toml"));
    config.save(&cfg_path)?;
    written.push(cfg_path.display().to_string());

    let unknowns = profile
        .unknowns
        .iter()
        .map(|u| format!("//   - {u}"))
        .collect::<Vec<_>>()
        .join("\n");
    let stub = format!(
        r#"//! Starter adapter for {name}, generated by `blockle inspect --generate-adapter`.
//!
//! Detected so far:
//!   dialect:    {dialect}
//!   algorithm:  {algo}
//!   template:   {tpl}
//!   submission: {sub}
//! Still unknown:
{unknowns}
//!
//! Implement the gaps below, then register the adapter in
//! `src/adapters/mod.rs` and reference it from the pool config
//! (`chain.adapter = "{name}"`).

use anyhow::Result;

use crate::adapter::{{BlockResult, Job, PoolAdapter, ShareOutcome, ShareSubmit}};
use crate::rpc::RpcClient;

pub struct {type_name}Adapter {{
    rpc: RpcClient,
}}

impl {type_name}Adapter {{
    pub fn new(rpc_url: &str) -> Self {{
        Self {{ rpc: RpcClient::new(rpc_url) }}
    }}
}}

impl PoolAdapter for {type_name}Adapter {{
    fn chain_name(&self) -> String {{
        "{name}".into()
    }}

    fn poll_job(&mut self, _refresh: bool) -> Result<Option<Job>> {{
        // TODO: fetch the template ({tpl}) and translate it into a stratum
        // job for this chain's work format.
        todo!("build jobs for {name}")
    }}

    fn check_share(&self, _job: &Job, _submit: &ShareSubmit) -> ShareOutcome {{
        // TODO: reconstruct the header and verify this chain's PoW ({algo}).
        todo!("validate {name} shares")
    }}

    fn submit_block(&self, _job: &Job, _submit: &ShareSubmit) -> BlockResult {{
        // TODO: assemble and submit the full block ({sub}).
        todo!("submit {name} blocks")
    }}

    fn block_reward(&self) -> Option<u64> {{
        None
    }}
}}
"#,
        name = name,
        type_name = {
            let mut c = name.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => "Custom".into(),
            }
        },
        dialect = profile.dialect,
        algo = profile.algorithm,
        tpl = profile.template_method.as_deref().unwrap_or("UNKNOWN"),
        sub = profile.submit_method.as_deref().unwrap_or("UNKNOWN"),
        unknowns = if unknowns.is_empty() { "//   (none)".to_string() } else { unknowns },
    );
    let stub_path = out_dir.join(format!("{name}_adapter.rs"));
    fs::write(&stub_path, stub)?;
    written.push(stub_path.display().to_string());
    Ok(written)
}
